### ISSUE TITLE
Integrate rabbitmq-cli-consumer

### ISSUE THREAD

**Issue by gsdevme** [usemarkup/JobQueueBundle#16]
1. `rabbitmq-cli-consumer` requires a configuration file per queue (see https://github.com/ricbra/rabbitmq-cli-consumer#configuration), this should be written out via a command within the JobQueue.
2. The Supervisord configuration file needs adapting to allow for the `rabbitmq-cli-consumer` to be ran instead.
3. A command needs adding to proxy the JobConsumer similar to the documentation. 

 https://github.com/ricbra/rabbitmq-cli-consumer

**Comment by calumbrodie** [comment]
This has been completed
