### ISSUE TITLE
Convert Job Log Implementation

### ISSUE THREAD

**Issue by calumbrodie** [usemarkup/JobQueueBundle#38]
Currently Redis is used for storing job logs there are numerous issues:
- Repository code is complicated and unmaintainable
- Implementing search options against jobs is laborious
- There are various edge case bugs with jobs being left in secondary indexes which breaks the job log completely
- hogs space in redis

My preference here is to move to using the database to store this information, at the same time making the 'retention' time for jobs maintainable via configuration (and maybe being able to disable logging completely).

**Comment by gsdevme** [comment]
This is now completed.
